	CREATE DATABASE QL_DULICH
	USE QL_DULICH
	GO

	CREATE TABLE CHUCVU
	(
		MACV VARCHAR(10),
		TENCV NVARCHAR(50),
		CONSTRAINT PK_CV PRIMARY KEY (MACV)
	)

	CREATE TABLE NHANVIEN
	(
		MANV VARCHAR(10),
		TENNV NVARCHAR(50),
		MACV VARCHAR(10),
		DIENTHOAI NVARCHAR(10),
		DIACHI NVARCHAR(50),
		NGAYSINH DATE,
		GIOITINH NVARCHAR(3),
		CONSTRAINT PK_NV PRIMARY KEY (MANV),
		CONSTRAINT FK_NV_CV FOREIGN KEY (MACV) REFERENCES CHUCVU(MACV)
	)

	CREATE TABLE KHACHHANG
	(
		MAKH VARCHAR(10),
		TENKH NVARCHAR(50),
		DIENTHOAI NVARCHAR(10),
		DIACHI NVARCHAR(50),
		GIOITINH NVARCHAR(3),
		CMND VARCHAR(10),
		NGAYSINH DATE,
		CONSTRAINT PK_KH PRIMARY KEY (MAKH)
	)

	CREATE TABLE CHUYEN
	(
		MACHUYEN VARCHAR(10),
		DIEMDI VARCHAR(10),
		DIEMDEN VARCHAR(10),
		CONSTRAINT PK_CHUYEN PRIMARY KEY (MACHUYEN),
	)

	CREATE TABLE KHACHSAN
	(
		MAKS VARCHAR(10),
		TENKS NVARCHAR(50),
		DIACHI NVARCHAR(50),
		DIENTHOAI NVARCHAR(10),
		CONSTRAINT PK_KS PRIMARY KEY (MAKS)
	)

	CREATE TABLE PHUONGTIEN
	(
		MAPT VARCHAR(10),
		TENPT NVARCHAR(50),
		SUCCHUA NVARCHAR(50),
		CONSTRAINT PK_PT PRIMARY KEY (MAPT)
	)

	CREATE TABLE TOUR
	(
		MATOUR VARCHAR(10),
		MACHUYEN VARCHAR(10),
		GIA FLOAT,
		THOIGIAN DATETIME,
		GHICHU NVARCHAR(100),
		MAPT VARCHAR(10),
		MAKS VARCHAR(10),
		NGAYDI DATE,
		CONSTRAINT PK_TOUR PRIMARY KEY (MATOUR),
		CONSTRAINT FK_TOUR_CHUYEN FOREIGN KEY (MACHUYEN) REFERENCES CHUYEN(MACHUYEN),	
		CONSTRAINT FK_TOUR_PT FOREIGN KEY (MAPT) REFERENCES PHUONGTIEN(MAPT),
		CONSTRAINT FK_TOUR_KS FOREIGN KEY (MAKS) REFERENCES KHACHSAN(MAKS)
	)

	CREATE TABLE PHIEUDKTOUR
	(
		MAPHIEU VARCHAR(10),
		TENPHIEU NVARCHAR(50),
		MAKH VARCHAR(10),
		MATOUR VARCHAR(10),
		CONSTRAINT PK_PHIEU PRIMARY KEY (MAPHIEU),
		CONSTRAINT FK_PHIEU_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),	
		CONSTRAINT FK_PHIEU_TOUR FOREIGN KEY (MATOUR) REFERENCES TOUR(MATOUR)
	)

	CREATE TABLE CHITIETDK
	(
		MAPHIEU VARCHAR(10),
		MAKH VARCHAR(10),
		CONSTRAINT PK_CHITIETDK PRIMARY KEY (MAPHIEU,MAKH),
		CONSTRAINT FK_CHITIETDK_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
		CONSTRAINT FK_CHITIETDK_PHIEUDKTOUR FOREIGN KEY (MAPHIEU) REFERENCES PHIEUDKTOUR(MAPHIEU)
	)

	CREATE TABLE PHANCONG
	(
		MANV VARCHAR(10),
		MATOUR VARCHAR(10),
		CONSTRAINT PK_PHANCONG PRIMARY KEY (MANV,MATOUR),
		CONSTRAINT FK_PC_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
		CONSTRAINT FK_PC_TOUR FOREIGN KEY (MATOUR) REFERENCES TOUR(MATOUR)
	)